import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  verifiedScreenContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  verifiedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    height: 60,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  verifiedUserInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  verifiedAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  verifiedBrandTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0052cc',
    marginLeft: 10,
  },
  verifiedBellButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifiedScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 36,
    paddingBottom: 100,
    alignItems: 'center',
  },
  checkmarkOuterCircle: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: '#DCFCE7',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#16A34A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
  },
  checkmarkInnerCircle: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifiedTitleText: {
    fontSize: 26,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 6,
  },
  verifiedSubtitleText: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 24,
    fontWeight: '500',
  },
  verifiedCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 20,
    marginBottom: 28,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardHeaderCol: {
    flex: 1,
  },
  cardMetaLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  cardMetaValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  dashedDividerContainer: {
    height: 1,
    overflow: 'hidden',
    marginVertical: 18,
  },
  dashedLine: {
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
    borderRadius: 1,
  },
  cardDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardDetailBold: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
  },
  cardDetailSub: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  cardDetailText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  slotBlueBadge: {
    backgroundColor: '#1E6091',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  slotBlueBadgeText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  statusGreenBadge: {
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusGreenBadgeText: {
    color: '#065F46',
    fontSize: 12,
    fontWeight: '800',
  },
  grayPillBox: {
    backgroundColor: '#F1F5F9',
    height: 48,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  grayPillText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  allowEntryBtn: {
    width: '100%',
    height: 54,
    borderRadius: 27,
    backgroundColor: '#004BB5',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 14,
    shadowColor: '#004BB5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  allowEntryBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  viewDetailsBtn: {
    width: '100%',
    height: 54,
    borderRadius: 27,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  viewDetailsBtnText: {
    color: '#334155',
    fontSize: 16,
    fontWeight: '700',
  },
  dummyTabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 64,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 4,
  },
  dummyTabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  dummyTabLabel: {
    fontSize: 10,
    color: '#6B7280',
    marginTop: 4,
    fontWeight: '600',
  },
  dummyActiveTab: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  dummyActiveTabLabel: {
    fontSize: 10,
    color: '#1E6091',
    marginTop: 4,
    fontWeight: '700',
  },
  successBanner: {
    backgroundColor: '#DCFCE7',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
  },
  successBannerText: {
    color: '#16A34A',
    fontWeight: '600',
    fontSize: 13,
    marginLeft: 8,
    flex: 1,
  },
});
